version: '3'

services:
  app:
    build: ./nodejs
    volumes:
      - ./nodejs:/home/node/app
    ports:
      - '3001:3000'

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
